services:
    sbot:
        container_name: sbot
        #image: FujiroAkakura/ssb-pub-underground
        build:
          context: .  #path to file
          dockerfile: Dockerfile
        #image: sbot  
        init: true #https://stackoverflow.com/questions/50356032/whats-the-docker-compose-equivalent-of-docker-run-init
        environment:
          EXAMPLE_EXAMPLE: example_example
        volumes:  #named volume: https://www.youtube.com/watch?v=p2PH_YPCsis
          - ~./ssb-pub-data:/root/.ssb/
        ports:
          - target: 8008
            published: 8008
            protocol: tcp
        restart: unless-stopped
        deploy:
          resources:
            limits:
              cpus: "1.0"
              memory: 500M
#volumes:
 # pub-data:



