kind: Namespace
apiVersion: v1
metadata:
  name: scuttlebutt
---
kind: Service
apiVersion: v1
metadata:
  name: ssb-pub
  namespace: scuttlebutt
spec:
  selector:
    app: ssb-pub
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssb-pvc
  namespace: scuttlebutt
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ssb-pub-deployment
  namespace: scuttlebutt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssb-pub
  template:
    metadata:
      labels:
        app: ssb-pub
    spec:
      containers:
        - name: ssb-pub
          image: ahdinosaur/ssb-pub
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - sbot
                - whoami
            initialDelaySeconds: 30
            periodSeconds: 300
          ports:
            - containerPort: 8008
          volumeMounts:
            - name: ssb-pub-volume
              mountPath: "/home/node/.ssb"
      volumes:
        - name: ssb-pub-volume
          persistentVolumeClaim:
            claimName: ssb-pvc
